Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        o = MockObject()
>       assert get_name(o) == "module.name"
E       AssertionError: assert 'name' == 'module.name'
E         
E         - module.name
E         + name

../test.py:15: AssertionError
=========================== short test summary info ============================
FAILED ../test.py::test - AssertionError: assert 'name' == 'module.name'
============================== 1 failed in 0.03s ===============================
